on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Rodar testes api via controller
        run: npm run test-rest-controller

      - name: Upload mochawesome report (controller)
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-controller
          path: mochawesome-report/

      - name: Subir a api rest
        run: npm run start &

      - name: Esperar as APIs estarem Funcionando
        run: sleep 8

      - name: Criar .env
        run: |
          echo "BASE_URL_REST=${{ secrets.BASE_URL_REST }}" >> .env

      - name: Rodar testes de api rest via HTTP
        run: npm run test-rest-external

      - name: Upload mochawesome report (external)
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-external
          path: mochawesome-report/
